#监控配置相关
management:
    endpoint:
        health:
            show-details: always
    endpoints:
        web:
            exposure:
                include: '*'
    metrics:
        tags:
            application: ${spring.application.name}
